// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/twilio.proto

package twilio

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Twilio service

func NewTwilioEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Twilio service

type TwilioService interface {
	SendSms(ctx context.Context, in *SendSmsRequest, opts ...client.CallOption) (*SendSmsResponse, error)
}

type twilioService struct {
	c    client.Client
	name string
}

func NewTwilioService(name string, c client.Client) TwilioService {
	return &twilioService{
		c:    c,
		name: name,
	}
}

func (c *twilioService) SendSms(ctx context.Context, in *SendSmsRequest, opts ...client.CallOption) (*SendSmsResponse, error) {
	req := c.c.NewRequest(c.name, "Twilio.SendSms", in)
	out := new(SendSmsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Twilio service

type TwilioHandler interface {
	SendSms(context.Context, *SendSmsRequest, *SendSmsResponse) error
}

func RegisterTwilioHandler(s server.Server, hdlr TwilioHandler, opts ...server.HandlerOption) error {
	type twilio interface {
		SendSms(ctx context.Context, in *SendSmsRequest, out *SendSmsResponse) error
	}
	type Twilio struct {
		twilio
	}
	h := &twilioHandler{hdlr}
	return s.Handle(s.NewHandler(&Twilio{h}, opts...))
}

type twilioHandler struct {
	TwilioHandler
}

func (h *twilioHandler) SendSms(ctx context.Context, in *SendSmsRequest, out *SendSmsResponse) error {
	return h.TwilioHandler.SendSms(ctx, in, out)
}
