name: Chat - Build, Push, Deploy
on:
  push:
    paths:
      - '.github/workflows/chat.yml'
      - 'chat/**'

jobs:
  build:
    name: Build, Push, Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Docker Build
        run: docker build -t m3o/chat .
        working-directory: ./chat
        
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Tag & Push Live
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag m3o/chat registry.digitalocean.com/m3o/chat:live
          docker push registry.digitalocean.com/m3o/chat:live
          doctl apps create-deployment ${{ secrets.DIGITALOCEAN_CHAT_ID }}
