name: Docker Images
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docker.yml'
      - 'cmd/micro-platform/**'
      - 'api/v1/**'
  repository_dispatch:
    types: [micro_release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
        id: go

      - name: Clone micro repo
        uses: actions/checkout@v2
        with:
          repository: "m3o/m3o"

      - name: Fetch tags
        run: git fetch --prune --unshallow

      - name: Build micro
        run: |
          cd cmd/micro-platform
          GOPROXY=direct go get github.com/micro/micro/v3@master
          GOPROXY=direct go get

      - name: Publish to platform image to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        working-directory: cmd/micro-platform
        with:
          name: m3o/platform
          username: ${{ secrets.GHCR_ACTOR }}
          password: ${{ secrets.GHCR_PAT }}
          snapshot: true
          registry: ghcr.io
