name: Platform Image
on:
  push:
    branches:
      - main
      - beta
    paths:
      - '.github/workflows/docker.yml'
      - 'platform/**'
  repository_dispatch:
    types: [micro_release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20.4
        uses: actions/setup-go@v1
        with:
          go-version: 1.20.4
        id: go

      - name: Clone m3o repo
        uses: actions/checkout@v2
        with:
          repository: "m3o/m3o"

      - name: Fetch tags
        run: git fetch --prune --unshallow

      - name: Build platform
        run: |
          cd platform
          GOPROXY=direct go get

      - name: Publish to platform image to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: m3o/platform
          username: ${{ secrets.GHCR_ACTOR }}
          password: ${{ secrets.GHCR_PAT }}
          snapshot: true
          registry: ghcr.io
          workdir: platform
