name: M3O Client Generation Scheduler
on:
  repository_dispatch:
    types: 
      - bp_m3o_client
      - bp_dart
      - bp_go
      - bp_ts
      - bp_shell

jobs:
  generate-dart:
    if: ${{ github.event.action == 'bp_dart' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger m3o/m3o-dart
        run: |
          curl -X POST -H "Authorization: token $GH_PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/m3o/m3o-dart/dispatches -d '{"event_type":"build_publish_dart"}'
        env:
          GH_PAT: ${{ secrets.API_TOKEN_GITHUB }}

  generate-go:
    if: ${{ github.event.action == 'bp_go' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger m3o/m3o-go
        run: |
          curl -X POST -H "Authorization: token $GH_PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/m3o/m3o-go/dispatches -d '{"event_type":"build_publish_go"}'
        env:
          GH_PAT: ${{ secrets.API_TOKEN_GITHUB }}